// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easymodels

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels(in *jlexer.Lexer, out *User) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "age":
			out.Age = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels(out *jwriter.Writer, in User) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Int(int(in.Age))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v User) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *User) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels(l, v)
}
func easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels1(in *jlexer.Lexer, out *PetStore) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "staff":
			if in.IsNull() {
				in.Skip()
				out.Staff = nil
			} else {
				in.Delim('[')
				if out.Staff == nil {
					if !in.IsDelim(']') {
						out.Staff = make([]*User, 0, 8)
					} else {
						out.Staff = []*User{}
					}
				} else {
					out.Staff = (out.Staff)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *User
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(User)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Staff = append(out.Staff, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "count":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels1(out *jwriter.Writer, in PetStore) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"staff\":"
		out.RawString(prefix[1:])
		if in.Staff == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Staff {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"count\":"
		out.RawString(prefix)
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PetStore) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels1(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PetStore) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels1(l, v)
}
func easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels2(in *jlexer.Lexer, out *Dog) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fav_toy":
			out.FavoriteToy = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels2(out *jwriter.Writer, in Dog) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fav_toy\":"
		out.RawString(prefix[1:])
		out.String(string(in.FavoriteToy))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Dog) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels2(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Dog) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels2(l, v)
}
func easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels3(in *jlexer.Lexer, out *Cat) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "fav_food":
			out.FavoriteFood = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels3(out *jwriter.Writer, in Cat) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"fav_food\":"
		out.RawString(prefix[1:])
		out.String(string(in.FavoriteFood))
	}
	out.RawByte('}')
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Cat) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3bf9eae0EncodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels3(w, v)
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Cat) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3bf9eae0DecodeGithubComMxv2FrontierGoEasyjsonPolyEasymodels3(l, v)
}
